[tool.poetry]
name = "skystore-cli"
version = "0.1.0"
description = "CLI for SkyStore"
authors = ["Shu Liu <lshu@berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"
typer = "*"
psutil = "*"
# Dependencies from store-server
fastapi = "*"
databases = "*"
uvicorn = {extras = ["standard"], version = "*"}
aiosqlite = "*"
pydantic = "*"
httpx = "*"
sqlalchemy = ">=2.0"
sqlalchemy_repr = "*"
rich = "*"
jq = "*"
greenlet = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
skystore = 'skystore_cli:app'